
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'benchmark_analysis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'benchmark_databricks'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  benchmark_analysis:
      # Applies to all files under models/example/
      
    staging:
        materialized: view


seeds:
    benchmark_analysis:
        +schema: raw
        +enabled: true
        +quote_columns: true

        
        # performance_logs:
        #     +column_types:
        #         timeStamp: string
        #         elapsed: string
        #         label: string
        #         responseCode: string
        #         responseMessage: string
        #         threadName: string
        #         dataType: string
        #         success: string
        #         failureMessage: string
        #         bytes: string
        #         sentBytes: string
        #         grpThreads: string
        #         allThreads: string
        #         URL: string
        #         Latency: string
        #         IdleTime: string
        #         Connect: string




                # timeStamp: int
                # elapsed: int
                # label: string
                # responseCode: int
                # responseMessage: string
                # threadName: string
                # dataType: string
                # success: boolean
                # failureMessage: string
                # bytes: int
                # sentBytes: int
                # grpThreads: int
                # allThreads: int
                # URL: string
                # Latency: int
                # IdleTime: int
                # Connect: int

                